name: collect-jobs
description: Collects all jobs in a workflow
inputs:
  JOB:
    description: 'Job name'
    required: true

runs:
  using: composite
  steps:
    - name: check jobs env
      if: ${{ env.JOBS != '' && env.JOBS != null }}
      shell: bash
      run: echo "JOBS=" >> $GITHUB_ENV
    - name: add jobs
      shell: bash
      env:
        JOBS: ${{ env.JOBS }}
        JOB: ${{ inputs.JOB }}
      run: |
        JOBS+=" $JOB"
        echo "JOBS=$JOBS" >> $GITHUB_ENV
    - name: echo jobs
      shell: bash
      run: echo "jobs - $JOBS"
       
        