name: collect-jobs
description: Collects all jobs in a workflow

runs:
  using: composite
  steps:
  shell: bash
    - name: Collect jobs
      run: |
        if [ -z "${{ env.JOBS }}" ]; then
          echo JOBS >> $GITHUB_ENV
        