name: collect-jobs
description: Collects all jobs in a workflow
inputs:
  JOB:
    description: 'Job name'
    required: true

runs:
  using: composite
  steps:
    - name: check jobs env
      if: ${{ !env.JOBS }}
      shell: bash
      run: echo "JOBS=default" >> $GITHUB_ENV
    - name: add jobs
      shell: bash
      env:
        JOBS: ${{ env.JOBS }}
        JOB: ${{ inputs.JOB }}
      run: echo "JOBS=\"${JOBS}, ${JOB}\"  >> $GITHUB_ENV
    - name: echo jobs
      shell: bash
      run: echo "jobs - $JOBS"
       
        