name: collect-jobs
description: Collects all jobs in a workflow

runs:
  using: composite
  steps:
    - name: Collect jobs
      shell: bash
      run: |
        if [ -z "${{ env.JOBS }}" ]; then
          echo JOBS >> $GITHUB_ENV
        