name: collect-jobs
description: Collects all jobs in a workflow

runs:
  using: composite
  steps:
    - name: check jobs env
      if: ${{ !env.JOBS }}
      shell: bash
      run: echo "JOBS=" >> $GITHUB_ENV
    - name: Collect jobs
      shell: bash
      env:
        JOBS: ${{ env.JOBS }}
      run: |
        if [ -z "$JOBS" ]; then \
          echo JOBS >> $GITHUB_ENV; \
        fi
        