name: jobs context poc

on: [push]

env:
  SLOBS: 

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: echo job-1
        run: echo "job-1"

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: echo job-2
        run: echo "job-2"

  job-3:
    runs-on: ubuntu-latest
    needs: job-2
    steps:
      - name: echo job-3
        run: |
          echo "job-3"
          exit 1

  job-4:
    runs-on: ubuntu-latest
    needs: [job-1, job-2, job-3]
    if: failure()
    steps:
      - name: find failed job
        env:
          JOBS: ${{ toJson(needs) }}
        run: |
          echo $JOBS | jq 'to_entries[] | select(.result == "failure" | .key)'
      # - name: report failure
      #   uses: ./.github/actions/reporter
      #   with:
      #     message: "job-4 failed"
