name: jobs context poc

on: [push]

env:
  SLOBS: 

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: echo job-1
        run: echo "job-1"
      - name: echo env
        run: echo "github env vars ${{ toJson(env) }}"
      - name: set jobs env
        uses: ../.github/actions/collect-jobs
      - name: persist jobname
        run: echo "github env vars ${{ toJson(env) }}"

  job-2:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: js hello
        run: node ./github/workfows/hello.js

  job-3:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: py hello
        run: python ./github/workfows/hello.py

  # jobs-context:
  #   runs-on: ubuntu-latest
  #   env:
  #     JOBS: 
  #   steps:
  #     - name: print jobs context
  #       run: |
  #         echo "jobs-context: ${{ toJson(jobs) }}"
  #         echo "job-1: ${{ toJson(jobs.job-1) }}"
  #         echo "job-2: ${{ toJson(jobs.job-2) }}"
  #         echo "job-3: ${{ toJson(jobs.job-3) }}"
