name: jobs context poc

on: [push]

env:
  SLOBS: 

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: echo env
        run: echo "github env vars ${{ toJson(env) }}"
      - name: set job name
        uses: ./.github/actions/collect-jobs
        with:
          JOB: job-1
      - name: echo jobs
        run: echo "github env vars ${{ toJson(env) }}"

  job-2:
    runs-on: ubuntu-latest
    container: node:14
    needs: job-1
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: js hello
        run: |
          pwd
          ls -la
          ls -la ./.github
          ls -la ./.github/workflows
          node ./.github/workflows/hello.js
      - name: set job name
        uses: ./.github/actions/collect-jobs
        with:
          JOB: job-2

  job-3:
    runs-on: ubuntu-latest
    container: python:3.8
    needs: job-2
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: py hello
        run: python ./.github/workflows/hello.py
      - name: set job name
        uses: ./.github/actions/collect-jobs
        with:
          JOB: job-3

  # jobs-context:
  #   runs-on: ubuntu-latest
  #   env:
  #     JOBS: 
  #   steps:
  #     - name: print jobs context
  #       run: |
  #         echo "jobs-context: ${{ toJson(jobs) }}"
  #         echo "job-1: ${{ toJson(jobs.job-1) }}"
  #         echo "job-2: ${{ toJson(jobs.job-2) }}"
  #         echo "job-3: ${{ toJson(jobs.job-3) }}"
