name: jobs context poc

on: [push]

env:
  SLOBS:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: echo job-1
        run: echo "job-1"
      - name: echo env
        run: echo "env: ${{ toJson(env) }}"
      # - name: persist jobname
      #   run: if [ -z "${{ env.JOBS }}" ]; then 

  job-2:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: js hello
        run: node ./hello.js

  job-3:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - name: py hello
        run: python ./hello.py

  jobs-context:
    runs-on: ubuntu-latest
    env:
      JOBS: 
    steps:
      - name: print jobs context
        run: |
          echo "jobs-context: ${{ toJson(jobs) }}"
          echo "job-1: ${{ toJson(jobs.job-1) }}"
          echo "job-2: ${{ toJson(jobs.job-2) }}"
          echo "job-3: ${{ toJson(jobs.job-3) }}"
