name: jobs context poc

# on: [push]
on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read

env:
  SLOBS: 

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: echo job-1
        run: echo "job-1"

  check-change:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: check change
        id: check_change
        run: |
          flag=$(git diff --name-only origin/${{ github.head_ref}}..origin/${{github.base_ref}} -- ./.github/workflows/scripts/**)
          if [ -z "$flag" ]; then
            echo "::set-output name=change::false"
          else
            echo "::set-output name=change::true"
          fi

  job-2:
    runs-on: ubuntu-latest
    needs: check-change
    if: ${{ needs.check-change.outputs.change == 'true' }}
    steps:
      - name: echo job-2
        run: echo "job-2"


  job-3:
    runs-on: ubuntu-latest
    needs: job-2
    steps:
      - name: echo job-3
        run: |
          echo "job-3"
          exit 1

  job-4:
    runs-on: ubuntu-latest
    needs: [job-1, job-2, job-3]
    if: failure()
    steps:
      - name: find failed job
        env:
          JOBS: ${{ toJson(needs) }}
        run: |
          FAILED_JOB=$(echo $JOBS | jq 'to_entries[] | select(.value.result == "failure") | .key')
          echo "FAILED_JOB=$FAILED_JOB" >> $GITHUB_ENV
      - name: report failed job
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: ${{ secrets.SENDGRID_USER }}
          password: ${{ secrets.SENDGRID_PASSWORD }}
          subject: 'Test Email'
          body: "Job ${{ env.FAILED_JOB }} failed"
          to: 'lxkdevtesting@gmail.com'
      
